"""
Pretrain the JourneyTransformer on synthetic sessions from Adobe click data.

Expects sessions/pretrain_train.jsonl and sessions/pretrain_val.jsonl
(generated by scripts/reconstruct_sessions.py).

Usage:
    conda run -n xaiml python scripts/pretrain.py
    conda run -n xaiml python scripts/pretrain.py --epochs 20 --batch-size 512
"""
import os
import math
import argparse
import json

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from tqdm import tqdm

from model.transformer import JourneyTransformer, journey_loss
from model.dataset import SessionDataset
from model.config import ModelConfig, TrainConfig, DEFAULT_MODEL, DEFAULT_TRAIN


def get_lr(step: int, d_model: int, warmup: int) -> float:
    """Transformer learning rate schedule (Vaswani et al.)."""
    step = max(step, 1)
    return d_model ** -0.5 * min(step ** -0.5, step * warmup ** -1.5)


def evaluate(model, loader, device):
    model.eval()
    total_loss = 0.0
    n_batches  = 0
    with torch.no_grad():
        for inp, tgt, msk in loader:
            inp, tgt, msk = inp.to(device), tgt.to(device), msk.to(device)
            logits = model(inp, pad_mask=msk)
            loss = journey_loss(logits, tgt)
            total_loss += loss.item()
            n_batches  += 1
    return total_loss / max(n_batches, 1)


def main():
    parser = argparse.ArgumentParser(description="Pretrain JourneyTransformer")
    parser.add_argument("--sessions-dir",  default="sessions")
    parser.add_argument("--ckpt-dir",      default="checkpoints")
    parser.add_argument("--epochs",        type=int,   default=DEFAULT_TRAIN.pretrain_epochs)
    parser.add_argument("--batch-size",    type=int,   default=DEFAULT_TRAIN.pretrain_batch)
    parser.add_argument("--warmup",        type=int,   default=DEFAULT_TRAIN.pretrain_warmup)
    parser.add_argument("--max-seq-len",   type=int,   default=DEFAULT_MODEL.max_seq_len)
    parser.add_argument("--d-model",       type=int,   default=DEFAULT_MODEL.d_model)
    parser.add_argument("--n-layers",      type=int,   default=DEFAULT_MODEL.n_layers)
    parser.add_argument("--n-heads",       type=int,   default=DEFAULT_MODEL.n_heads)
    parser.add_argument("--d-ffn",         type=int,   default=DEFAULT_MODEL.d_ffn)
    parser.add_argument("--dropout",       type=float, default=DEFAULT_MODEL.dropout)
    parser.add_argument("--resume",        type=str,   default=None, help="Resume from checkpoint path")
    args = parser.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    os.makedirs(args.ckpt_dir, exist_ok=True)

    # ── Datasets ───────────────────────────────────────────────────────────────
    train_path = os.path.join(args.sessions_dir, "pretrain_train.jsonl")
    val_path   = os.path.join(args.sessions_dir, "pretrain_val.jsonl")

    if not os.path.exists(train_path):
        raise FileNotFoundError(
            f"{train_path} not found. Run scripts/reconstruct_sessions.py first."
        )

    train_ds = SessionDataset(train_path, max_seq_len=args.max_seq_len)
    val_ds   = SessionDataset(val_path,   max_seq_len=args.max_seq_len) \
               if os.path.exists(val_path) else None

    train_loader = DataLoader(train_ds, batch_size=args.batch_size,
                              shuffle=True,  num_workers=4, pin_memory=True)
    val_loader   = DataLoader(val_ds,   batch_size=args.batch_size * 2,
                              shuffle=False, num_workers=2, pin_memory=True) \
                   if val_ds else None

    print(f"Train: {len(train_ds)} sessions | Val: {len(val_ds) if val_ds else 0}")

    # ── Model ──────────────────────────────────────────────────────────────────
    cfg = ModelConfig(
        d_model=args.d_model, n_heads=args.n_heads, n_layers=args.n_layers,
        d_ffn=args.d_ffn, dropout=args.dropout, max_seq_len=args.max_seq_len,
    )
    model = JourneyTransformer(cfg).to(device)
    print(f"Parameters: {model.num_parameters():,}")

    # ── Optimiser (no scheduler object — compute LR manually) ─────────────────
    optimizer = torch.optim.Adam(model.parameters(), lr=1.0, betas=(0.9, 0.98), eps=1e-9)

    start_epoch = 0
    global_step = 0

    if args.resume:
        ckpt = torch.load(args.resume, map_location=device)
        model.load_state_dict(ckpt["model"])
        optimizer.load_state_dict(ckpt["optimizer"])
        start_epoch  = ckpt.get("epoch", 0) + 1
        global_step  = ckpt.get("global_step", 0)
        print(f"Resumed from {args.resume} (epoch {start_epoch})")

    # ── Training loop ──────────────────────────────────────────────────────────
    log = []
    best_val_loss = float("inf")

    for epoch in range(start_epoch, start_epoch + args.epochs):
        model.train()
        epoch_loss = 0.0
        n_batches  = 0

        pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{start_epoch + args.epochs}")
        for inp, tgt, msk in pbar:
            inp, tgt, msk = inp.to(device), tgt.to(device), msk.to(device)

            # Update learning rate
            global_step += 1
            lr = get_lr(global_step, args.d_model, args.warmup)
            for pg in optimizer.param_groups:
                pg["lr"] = lr

            optimizer.zero_grad()
            logits = model(inp, pad_mask=msk)
            loss   = journey_loss(logits, tgt)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            epoch_loss += loss.item()
            n_batches  += 1
            pbar.set_postfix(loss=f"{loss.item():.4f}", lr=f"{lr:.2e}")

        avg_train_loss = epoch_loss / n_batches

        # Validation
        avg_val_loss = evaluate(model, val_loader, device) if val_loader else None

        log_entry = {
            "epoch":      epoch + 1,
            "train_loss": round(avg_train_loss, 5),
            "val_loss":   round(avg_val_loss, 5) if avg_val_loss else None,
            "lr":         round(lr, 7),
        }
        log.append(log_entry)
        print(json.dumps(log_entry))

        # Save checkpoint
        ckpt = {
            "epoch":       epoch,
            "global_step": global_step,
            "model":       model.state_dict(),
            "optimizer":   optimizer.state_dict(),
            "config":      cfg.__dict__,
            "train_loss":  avg_train_loss,
            "val_loss":    avg_val_loss,
        }
        ckpt_path = os.path.join(args.ckpt_dir, f"pretrain_epoch{epoch+1:03d}.pt")
        torch.save(ckpt, ckpt_path)

        # Save best
        if avg_val_loss is not None and avg_val_loss < best_val_loss:
            best_val_loss = avg_val_loss
            torch.save(ckpt, os.path.join(args.ckpt_dir, "pretrain_best.pt"))
            print(f"  → New best val loss: {best_val_loss:.5f}")

    # Save training log
    with open(os.path.join(args.ckpt_dir, "pretrain_log.json"), "w") as f:
        json.dump(log, f, indent=2)

    print(f"\nPretraining complete. Best val loss: {best_val_loss:.5f}")
    print(f"Best checkpoint: {os.path.join(args.ckpt_dir, 'pretrain_best.pt')}")


if __name__ == "__main__":
    main()
